.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Christopher Baines <cbaines8@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DBF-RB 1 "February 23, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dbf-rb \- command-line utility for the DBF library
.SH SYNOPSIS
.B dbf-rb
.RI [-h|-s|-a] " filename"
.SH DESCRIPTION
DBF is a small fast library for reading dBase, xBase, Clipper and FoxPro database files.
.PP
\fBdbf-rb\fP is a command-line utility for the Ruby DBF library.
.SH OPTIONS
.TP
.B \-s
print summary information.
.TP
.B \-a
create an ActiveRecord::Schema.
.TP
.B \-c
create a csv file.
.TP
.B \-h
Show summary of options.
.SH EXAMPLES
.TP
.B dbf-rb -a books.dbf > books_schema.rb
Create an ActiveRecord::Schema from the books database.
.TP
.B dbf-rb -c books.dbf > books.csv
Dump all records in books.dbf in to a CSV file.
